// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725040247_AddDonViToVanBanPhapLuat")]
    partial class AddDonViToVanBanPhapLuat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.AttachedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayBanHanh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<string>("SoVanBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("AttachedFiles");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachedFileGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DanhMucTrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DanhMucVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHoSo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLanTraLaiHienTai")
                        .HasColumnType("int");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuocHienTaiId");

                    b.HasIndex("DanhMucTrangThaiId");

                    b.HasIndex("DanhMucVanBanId");

                    b.HasIndex("DonViSoanThaoId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("QuyTrinhSoanThaoId");

                    b.ToTable("HoSoVanBans");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanBuocThoiHan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoSoVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoNgayCanhBaoSapHan")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayXuLy")
                        .HasColumnType("int");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuocQuyTrinhId");

                    b.HasIndex("HoSoVanBanId");

                    b.ToTable("HoSoVanBanBuocThoiHans");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanDanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachedFileGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViDanhGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoSoVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetQuaDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDanhGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TraLaiBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YeuCauChinhSua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuocQuyTrinhId");

                    b.HasIndex("DonViDanhGiaId");

                    b.HasIndex("HoSoVanBanId");

                    b.HasIndex("NguoiDanhGiaId");

                    b.HasIndex("TraLaiBuocId");

                    b.ToTable("HoSoVanBanDanhGias");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanLayYKien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachedFileGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViDuocLayYKienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDuocLayYKienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungPhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungYeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiPhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuocQuyTrinhId");

                    b.HasIndex("DonViDuocLayYKienId");

                    b.HasIndex("HoSoVanBanId");

                    b.HasIndex("NguoiDuocLayYKienId");

                    b.ToTable("HoSoVanBanLayYKiens");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanPhanHoiDanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachedFileGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HoSoVanBanDanhGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiPhanHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungGiaiTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonViSoanThaoId");

                    b.HasIndex("HoSoVanBanDanhGiaId");

                    b.HasIndex("HoSoVanBanId");

                    b.HasIndex("NguoiPhanHoiId");

                    b.ToTable("HoSoVanBanPhanHoiDanhGias");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DanhMucTrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("KetQuaXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanXuLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuocQuyTrinhId");

                    b.HasIndex("DanhMucTrangThaiId");

                    b.HasIndex("DonViXuLyId");

                    b.HasIndex("HoSoVanBanId");

                    b.HasIndex("NguoiXuLyId");

                    b.ToTable("HoSoVanBanXuLys");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionNameDanhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionNameXetDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerNameDanhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerNameXetDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViDongChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViGui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViTiepNhan")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("DonViView")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterDanhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterXetDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<string>("CachHoanThanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChoPhepBoQua")
                        .HasColumnType("bit");

                    b.Property<bool>("ChoPhepQuayLui")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViTiepNhanMacDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLanTraLaiToiDa")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongPhanHoiToiThieu")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayCanhBaoSapHan")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayXuLyTieuChuan")
                        .HasColumnType("int");

                    b.Property<string>("TenBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonViTiepNhanMacDinhId");

                    b.HasIndex("QuyTrinhSoanThaoId");

                    b.ToTable("DanhMucBuocQuyTrinhs");
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucChuyenBuocQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DieuKienKetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaNhanhMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DenBuocId");

                    b.HasIndex("QuyTrinhSoanThaoId");

                    b.HasIndex("TuBuocId");

                    b.ToTable("DanhMucChuyenBuocQuyTrinhs");
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucQuyTrinhSoanThao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DanhMucVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DanhMucVanBanIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuyTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucVanBanId");

                    b.ToTable("DanhMucQuyTrinhSoanThaos");
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucTrangThai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMauHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucTrangThais");
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapChinhQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuTheBanHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyHieuMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucVanBans");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucCanBo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViQuanLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiLaoDong")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucPhiBaoHiemTrachNhiem")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("NgayKyHopDongLaoDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhBoNhiem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhCapThe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTuyenDung")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoHopDongLaoDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhBoNhiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhCapThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTheCongChungVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienBHXH")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("SoTienBHYT")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TenCanBo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ViTriViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViQuanLyId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("DanhMucCanBos");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucDiaDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiaDanhCapTrenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("STTSapXep")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDiaDanhs");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucDonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucDanhQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViChuQuanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoVaTenNguoiQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaQHNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STTSapXep")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhNangThanhToan")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDonVis");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucPhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DanhMucDonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoaiPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucDonViId");

                    b.ToTable("DanhMucPhongBans");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.ThuTucHanhChinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CachThucThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanCuPhapLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoQuanThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoiTuongThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQuaThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LePhi")
                        .HasColumnType("float");

                    b.Property<string>("MaThuTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<double>("Phi")
                        .HasColumnType("float");

                    b.Property<string>("TenQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPhanHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanGiaiQuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhTuThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YeuCauDieuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThuTucHanhChinhs");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.GroupPermision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GroupsPermision");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.OptionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OptionDatas");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approve")
                        .HasColumnType("bit");

                    b.Property<bool>("Create")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit");

                    b.Property<Guid>("GroupPermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.RoleAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("STTSapXep")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UseGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleActions");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChatBot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOPT")
                        .HasColumnType("bit");

                    b.Property<int>("LoginLock")
                        .HasColumnType("int");

                    b.Property<DateTime>("MfgDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Train")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.Systems.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucDanhKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DanhMucDonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoanhNghiepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("bit");

                    b.Property<Guid>("GroupPermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoTenNguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyHieuDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTPSecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SSA")
                        .HasColumnType("bit");

                    b.Property<string>("ScanDeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanDeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuanBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VNId")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBan", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("BuocHienTaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucTrangThai", null)
                        .WithMany()
                        .HasForeignKey("DanhMucTrangThaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucVanBan", null)
                        .WithMany()
                        .HasForeignKey("DanhMucVanBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViSoanThaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Systems.User", null)
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucQuyTrinhSoanThao", null)
                        .WithMany()
                        .HasForeignKey("QuyTrinhSoanThaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanBuocThoiHan", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("BuocQuyTrinhId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBan", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanDanhGia", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("BuocQuyTrinhId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViDanhGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBan", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Systems.User", null)
                        .WithMany()
                        .HasForeignKey("NguoiDanhGiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("TraLaiBuocId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanLayYKien", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("BuocQuyTrinhId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViDuocLayYKienId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBan", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Systems.User", null)
                        .WithMany()
                        .HasForeignKey("NguoiDuocLayYKienId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanPhanHoiDanhGia", b =>
                {
                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViSoanThaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBanDanhGia", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanDanhGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBan", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Systems.User", null)
                        .WithMany()
                        .HasForeignKey("NguoiPhanHoiId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Entities.Manages.HoSoVanBanXuLy", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("BuocQuyTrinhId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucTrangThai", null)
                        .WithMany()
                        .HasForeignKey("DanhMucTrangThaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViXuLyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Manages.HoSoVanBan", null)
                        .WithMany()
                        .HasForeignKey("HoSoVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Systems.User", null)
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", b =>
                {
                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViTiepNhanMacDinhId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucQuyTrinhSoanThao", null)
                        .WithMany()
                        .HasForeignKey("QuyTrinhSoanThaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucChuyenBuocQuyTrinh", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("DenBuocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucQuyTrinhSoanThao", null)
                        .WithMany()
                        .HasForeignKey("QuyTrinhSoanThaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("TuBuocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.QuanLyDanhMuc.DanhMucQuyTrinhSoanThao", b =>
                {
                    b.HasOne("DataAccess.Entities.QuanLyDanhMuc.DanhMucVanBan", null)
                        .WithMany()
                        .HasForeignKey("DanhMucVanBanId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucCanBo", b =>
                {
                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", "DonViQuanLy")
                        .WithMany()
                        .HasForeignKey("DonViQuanLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Settings.DanhMucPhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonViQuanLy");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucPhongBan", b =>
                {
                    b.HasOne("DataAccess.Entities.Settings.DanhMucDonVi", "DanhMucDonVi")
                        .WithMany("DanhMucPhongBans")
                        .HasForeignKey("DanhMucDonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucDonVi");
                });

            modelBuilder.Entity("DataAccess.Entities.Settings.DanhMucDonVi", b =>
                {
                    b.Navigation("DanhMucPhongBans");
                });
#pragma warning restore 612, 618
        }
    }
}
